name: 'pr-type-check'
description: 'check of pr in visactor'
author: 'xile611'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  pull_request_body:
    description: 'the body of pull request'
    required: true
  pull_request_head:
    description: 'the head branch of pull request'
    required: true
# Define your outputs here.
outputs:
  result:
    description: 'Is the body of pull request validate or not'

runs:
  using: node20
  main: dist/index.js
